version: 2

models:
  - name: customers
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders

    tests:
      - validate_null_counts:
          table: ['customers']

    columns:

    - name: most_recent_order
      tests:
        - not_null

    - name: number_of_orders
      tests:
        - not_null

    - name: first_order
      tests:
        - not_null

    - name: customer_lifetime_value
      tests:
        - not_null
    
        
      

    

      


         
      
  - name: orders
    description: This table has basic information about orders, as well as some derived facts based on payments

    tests:
      - validate_null_counts:
          table: ['orders']

        columns:
    
    - name: bank_transfer_amount
      tests:
        - not_null
        
    - name: credit_card_amount
      tests:
        - not_null
        
    - name: coupon_amount
      tests:
        - not_null
        
    - name: amount
      tests:
        - not_null
        
    - name: gift_card_amount
      tests:
        - not_null      

   



   
      